# Generated by Django 3.2 on 2021-04-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.IntegerField()),
                ('paymentMethod', models.CharField(max_length=255)),
                ('taxprice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('shippingPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('isPaid', models.BooleanField()),
                ('paidAt', models.IntegerField()),
                ('isDelivered', models.IntegerField()),
                ('deliveredAt', models.DateTimeField()),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('product', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.IntegerField(null=True)),
                ('product', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pinCode', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('shippingprice', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('isStaff', models.BooleanField()),
                ('isActive', models.BooleanField()),
                ('isSuperuser', models.BooleanField()),
            ],
        ),
    ]
